CREATE TABLE IF NOT EXISTS schema_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(100) NOT NULL,
    name VARCHAR(200) NOT NULL,
    dialect VARCHAR(50) NOT NULL,
    ddl_text TEXT NOT NULL,
    description VARCHAR(2000),
    status VARCHAR(30) NOT NULL DEFAULT 'PUBLISHED',
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS semantic_synonym (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(100) NOT NULL,
    business_term VARCHAR(200) NOT NULL,
    synonyms VARCHAR(1000) NOT NULL,
    target_expression VARCHAR(1000) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PUBLISHED',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sql_example (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(100) NOT NULL,
    question VARCHAR(2000) NOT NULL,
    sql_text TEXT NOT NULL,
    explanation VARCHAR(2000),
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    version INTEGER NOT NULL DEFAULT 1,
    hit_count BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS golden_question (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR(100) NOT NULL,
    question VARCHAR(2000) NOT NULL,
    expected_sql TEXT,
    expected_result_json TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'ENABLED',
    last_run_status VARCHAR(30),
    last_score DECIMAL(8,4),
    last_detail VARCHAR(2000),
    last_run_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_asset(domain,name,dialect,ddl_text,description,status) VALUES
('sales','销售演示库','Oracle 19c','region -> customer -> sales_order -> sales_order_item；sales_order -> refund','演示销售域核心表结构与关系摘要','PUBLISHED');

INSERT INTO semantic_synonym(domain,business_term,synonyms,target_expression,status) VALUES
('sales','净销售额','实际销售额,销售净额,净营收','net_sales','PUBLISHED'),
('sales','华东','东区,华东区,East','region.region_code=EAST','PUBLISHED');

INSERT INTO sql_example(domain,question,sql_text,explanation,status) VALUES
('sales','查询2026年华东区域每月净销售额','WITH refund_by_order AS (SELECT order_id,SUM(refund_amount) refund_amount FROM refund WHERE refund_status=''COMPLETED'' GROUP BY order_id), order_amount AS (SELECT o.order_id,o.order_date,c.region_id,SUM(i.quantity*i.unit_price-i.discount_amount) gross_sales,COALESCE(r.refund_amount,0) refund_amount FROM sales_order o JOIN customer c ON c.customer_id=o.customer_id JOIN sales_order_item i ON i.order_id=o.order_id LEFT JOIN refund_by_order r ON r.order_id=o.order_id WHERE o.order_status=''COMPLETED'' GROUP BY o.order_id,o.order_date,c.region_id,r.refund_amount) SELECT EXTRACT(MONTH FROM oa.order_date) month_no,SUM(oa.gross_sales-oa.refund_amount) net_sales FROM order_amount oa JOIN region rg ON rg.region_id=oa.region_id WHERE rg.region_name=''华东'' AND EXTRACT(YEAR FROM oa.order_date)=2026 GROUP BY EXTRACT(MONTH FROM oa.order_date) ORDER BY month_no','退款先按订单聚合，按订单月份汇总','PUBLISHED');

INSERT INTO golden_question(domain,question,expected_result_json,status) VALUES
('sales','查询2026年华东区域每月净销售额','[{"month_no":1,"net_sales":890000},{"month_no":2,"net_sales":780000},{"month_no":3,"net_sales":510000}]','ENABLED');
