CREATE TABLE schema_asset (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR2(100 CHAR) NOT NULL,
    name VARCHAR2(200 CHAR) NOT NULL,
    dialect VARCHAR2(50 CHAR) NOT NULL,
    ddl_text CLOB NOT NULL,
    description VARCHAR2(2000 CHAR),
    status VARCHAR2(30 CHAR) DEFAULT 'PUBLISHED' NOT NULL,
    version NUMBER(10) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE semantic_synonym (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR2(100 CHAR) NOT NULL,
    business_term VARCHAR2(200 CHAR) NOT NULL,
    synonyms VARCHAR2(1000 CHAR) NOT NULL,
    target_expression VARCHAR2(1000 CHAR) NOT NULL,
    status VARCHAR2(30 CHAR) DEFAULT 'PUBLISHED' NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE sql_example (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR2(100 CHAR) NOT NULL,
    question VARCHAR2(2000 CHAR) NOT NULL,
    sql_text CLOB NOT NULL,
    explanation VARCHAR2(2000 CHAR),
    status VARCHAR2(30 CHAR) DEFAULT 'DRAFT' NOT NULL,
    version NUMBER(10) DEFAULT 1 NOT NULL,
    hit_count NUMBER(19) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE golden_question (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain VARCHAR2(100 CHAR) NOT NULL,
    question VARCHAR2(2000 CHAR) NOT NULL,
    expected_sql CLOB,
    expected_result_json CLOB,
    status VARCHAR2(30 CHAR) DEFAULT 'ENABLED' NOT NULL,
    last_run_status VARCHAR2(30 CHAR),
    last_score NUMBER(8,4),
    last_detail VARCHAR2(2000 CHAR),
    last_run_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

INSERT INTO schema_asset(domain,name,dialect,ddl_text,description,status)
VALUES ('sales','销售演示库','Oracle 19c','region -> customer -> sales_order -> sales_order_item；sales_order -> refund','演示销售域核心表结构与关系摘要','PUBLISHED');

INSERT INTO semantic_synonym(domain,business_term,synonyms,target_expression,status)
VALUES ('sales','净销售额','实际销售额,销售净额,净营收','net_sales','PUBLISHED');
INSERT INTO semantic_synonym(domain,business_term,synonyms,target_expression,status)
VALUES ('sales','华东','东区,华东区,East','region.region_code=EAST','PUBLISHED');

INSERT INTO sql_example(domain,question,sql_text,explanation,status)
VALUES (
  'sales',
  '查询2026年华东区域每月净销售额',
  'WITH refund_by_order AS (SELECT order_id,SUM(refund_amount) refund_amount FROM refund WHERE refund_status=''COMPLETED'' GROUP BY order_id), order_amount AS (SELECT o.order_id,o.order_date,c.region_id,SUM(i.quantity*i.unit_price-i.discount_amount) gross_sales,COALESCE(r.refund_amount,0) refund_amount FROM sales_order o JOIN customer c ON c.customer_id=o.customer_id JOIN sales_order_item i ON i.order_id=o.order_id LEFT JOIN refund_by_order r ON r.order_id=o.order_id WHERE o.order_status=''COMPLETED'' GROUP BY o.order_id,o.order_date,c.region_id,r.refund_amount) SELECT EXTRACT(MONTH FROM oa.order_date) month_no,SUM(oa.gross_sales-oa.refund_amount) net_sales FROM order_amount oa JOIN region rg ON rg.region_id=oa.region_id WHERE rg.region_name=''华东'' AND EXTRACT(YEAR FROM oa.order_date)=2026 GROUP BY EXTRACT(MONTH FROM oa.order_date) ORDER BY month_no',
  '退款先按订单聚合，再按订单月份汇总。',
  'PUBLISHED'
);

INSERT INTO golden_question(domain,question,expected_result_json,status)
VALUES ('sales','查询2026年华东区域每月净销售额','[{"month_no":1,"net_sales":890000},{"month_no":2,"net_sales":780000},{"month_no":3,"net_sales":510000}]','ENABLED');
