CREATE TABLE app_user (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    password_hash VARCHAR2(100 CHAR) NOT NULL,
    display_name VARCHAR2(200 CHAR) NOT NULL,
    enabled NUMBER(1) DEFAULT 1 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_app_user_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE app_role (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    name VARCHAR2(200 CHAR) NOT NULL
);

CREATE TABLE app_permission (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    name VARCHAR2(200 CHAR) NOT NULL
);

CREATE TABLE app_user_role (
    user_id NUMBER NOT NULL,
    role_id NUMBER NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES app_role(id)
);

CREATE TABLE app_role_permission (
    role_id NUMBER NOT NULL,
    permission_id NUMBER NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES app_role(id),
    CONSTRAINT fk_role_permission_perm FOREIGN KEY (permission_id) REFERENCES app_permission(id)
);

CREATE TABLE auth_session (
    id VARCHAR2(36 CHAR) PRIMARY KEY,
    user_id NUMBER NOT NULL,
    token_hash VARCHAR2(64 CHAR) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    revoked NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT ck_auth_session_revoked CHECK (revoked IN (0, 1)),
    CONSTRAINT fk_auth_session_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE INDEX idx_auth_session_user ON auth_session(user_id);
CREATE INDEX idx_auth_session_expiry ON auth_session(expires_at);

INSERT INTO app_permission(code, name) VALUES ('DATA_QUERY', '数据问答');
INSERT INTO app_permission(code, name) VALUES ('SMART_REPORT', '智能报告');
INSERT INTO app_permission(code, name) VALUES ('AI_TRAINING', 'AI 训练中心');

INSERT INTO app_role(code, name) VALUES ('ANALYST', '数据分析用户');
INSERT INTO app_role(code, name) VALUES ('REPORTER', '报告用户');
INSERT INTO app_role(code, name) VALUES ('AI_ADMIN', 'AI 管理员');

INSERT INTO app_role_permission(role_id, permission_id)
SELECT r.id, p.id FROM app_role r CROSS JOIN app_permission p
WHERE r.code = 'ANALYST' AND p.code = 'DATA_QUERY';
INSERT INTO app_role_permission(role_id, permission_id)
SELECT r.id, p.id FROM app_role r CROSS JOIN app_permission p
WHERE r.code = 'REPORTER' AND p.code IN ('DATA_QUERY', 'SMART_REPORT');
INSERT INTO app_role_permission(role_id, permission_id)
SELECT r.id, p.id FROM app_role r CROSS JOIN app_permission p
WHERE r.code = 'AI_ADMIN';

-- All local acceptance accounts use Aibi@123. Override/remove them before production deployment.
INSERT INTO app_user(username, password_hash, display_name, enabled)
VALUES ('question_user', '$2b$10$FhgxfaSL24kUtM/0JWR2GuesF/3KuxvuWYyM1SG2Q1Zx7CJmxm.xm', '数据问答用户', 1);
INSERT INTO app_user(username, password_hash, display_name, enabled)
VALUES ('report_user', '$2b$10$A8ooqc4ScmrY7pmqXxsHnumIJBZlXFEFJfHxMkVg0LpRmXWzDBfNa', '智能报告用户', 1);
INSERT INTO app_user(username, password_hash, display_name, enabled)
VALUES ('ai_admin', '$2b$10$M4lXAza/Q5TGehAQHaUBVusrXDx1NnuFCrm1tOQvZsGc4bt7M4No.', 'AI 管理员', 1);

INSERT INTO app_user_role(user_id, role_id)
SELECT u.id, r.id FROM app_user u CROSS JOIN app_role r WHERE u.username = 'question_user' AND r.code = 'ANALYST';
INSERT INTO app_user_role(user_id, role_id)
SELECT u.id, r.id FROM app_user u CROSS JOIN app_role r WHERE u.username = 'report_user' AND r.code = 'REPORTER';
INSERT INTO app_user_role(user_id, role_id)
SELECT u.id, r.id FROM app_user u CROSS JOIN app_role r WHERE u.username = 'ai_admin' AND r.code = 'AI_ADMIN';
